* 变量

通常我们会在项目里使用 eslint 这样的工具来帮我们规范代码的风格等， 不过在使用变量这一块，还是有些原则或则技巧很有帮助。

** 变量的使用

首先，变量在使用前，必须先声明。这是为了避免意外的创建了全局变量。

*** 变量的初始化

声明变量的同时，建议给变量初始化一个值，并且初始化的值，要符合变量要存储的值的类型，请看下面的例子：

#+BEGIN_SRC javascript
// name 这个变量从名字上很明显看出来要存储的是一个字符串
let name = ""; 
// 所以, 请不要像下面这样做
let name = 1; // 这个是错误的
 // age 存储的值很明显是数值类型
let age = 0;
// 所以, 请不要给 age 初始化一个数值以外的值
let age = false; // 这个是错误的
#+END_SRC


遵循*就近原则*，在靠近第一次使用变量的位置声明和定义该变量，比如：

#+BEGIN_SRC javascript
// 这是不好的做法
function test() {
  let age = 0;

  // ... 这里省略了一些代码

  // 变量在这里才被用到
  console.log(age);
}

// 推荐的做法是
function test() {
  // ... 这里省略了一些代码

  // 变量在这里才被用到
  let age = 0;
  console.log(age);
}
#+END_SRC


记得检查是否需要重新初始化。这是由于某些变量会被重复使用，请看下面的例子：

#+BEGIN_SRC javascript
function test() {
  let sending = false; // 是否正在发起网络请求

  sending = true;
  axios.get("/test1").then(function(){
    sending = false;
  });

  sending = true; // 在这里, 记得把变量设置为 true
  axios.get("/test2").then(function(){
    sending = false;
  });
}
#+END_SRC


*** 变量的作用域

作用域或则可见性指的是变量在程序内的可见和可引用的范围。一般来说，我们需要尽可能的避免使用全局变量，因为全局变量往往意味着“牵一发而动全身”，对全局变量的值的修改，往往更有可能出现问题。所以我们尽可能使用局部变量，并且把他的作用域限制在子程序内部。


*** 单一职责

确保每个变量只用于单一用途。当你给一个变量赋予多个职责的时候，这通常是因为对这个变量的命名不合适，或则使用了一个临时变量（temp 或则 x），请看下面的例子：

#+BEGIN_SRC javascript
// 糟糕的示范
let temp = 5 * 10;
console.log(temp);
temp = 1 + 2;
console.log(temp);

// 推荐的做法是分别给他们起一个符合含义的名字

let multiplication = 5 * 10;
console.log(multiplication);
let add = 1 + 2;
console.log(add);
#+END_SRC

另一种让变量用于多个用途的方式是当变量代表不同的实物时让他具有不同的取值集合，比如：

#+BEGIN_SRC javascript
let read = -1; // -1 表示读取文件的过程中发生了错误
read = 100; // 表示已经读了 100 个字节
#+END_SRC

** 起一个好的变量名

1. 为变量命名的时候，要考虑改名字要完全、准切地描述出变量所代表的事物。
2. 合适的使用缩写，控制名字的长度。

下面列举一下典型的布尔变量名：

1. done 表示某件事已经完成
2. error 表示有错误发生
3. found 表示某个值被找到了
4. success 或 ok 表示某一项操作是否成功

我们推荐使用肯定的布尔变量名，否定的变量名例如 notFound、notDone会比较难以阅读，特别是对他们求反的时候： ~if not notFound~ 。


** Magic Number

避免使用*神秘数值(magic number)*。它是再程序中出现的、没有经过解释的数值字面量，比如 100 或则 1024。 

关于神秘数值带来的问题， 我们可以想象一个场景，一个书架上，一开始最多可以放 100 本书，但是后来你发现现在最多可以放 120 本书，那么，在使用神秘数值的情况下，你需要在代码里进行文本搜索 100， 然后把每一个出现的地方都修改成 120，并且，你可能会一不小心，把书籍的最大单价 100 元也一起修改成了 120 元。

所以，通过上面的场景，你会发现为了避免这个问题，我们应该使用一个常量来表示，比如 ~const Maximum = 100;~ 。
